// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKjIMKMWl3z0cf7m33Zcc-ecz9vXeTow',
    appId: '1:52817147789:web:460d701217d7bb6306afc4',
    messagingSenderId: '52817147789',
    projectId: 'parked-793e0',
    authDomain: 'parked-793e0.firebaseapp.com',
    databaseURL: 'https://parked-793e0-default-rtdb.firebaseio.com',
    storageBucket: 'parked-793e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7EXo-yYfG-d3mWvsXLg8gxLYhuMpoeG8',
    appId: '1:52817147789:android:1e06d121038d292b06afc4',
    messagingSenderId: '52817147789',
    projectId: 'parked-793e0',
    databaseURL: 'https://parked-793e0-default-rtdb.firebaseio.com',
    storageBucket: 'parked-793e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChsqASLR_ungny5_MwSDZ9zAs8NfT0L0Y',
    appId: '1:52817147789:ios:267152585e00930806afc4',
    messagingSenderId: '52817147789',
    projectId: 'parked-793e0',
    databaseURL: 'https://parked-793e0-default-rtdb.firebaseio.com',
    storageBucket: 'parked-793e0.appspot.com',
    iosBundleId: 'com.muhammadali.riderApp',
  );
}
