import 'package:flutter/material.dart';
import 'Diya_timer.dart';
int timeDiff = 00;
int finaltimeDiff = 00;
int currentTimeInt = 00;
int startTimeInt = 00;
int endTimeInt = 00;
int nowTimeInt = 00;
bool On=false;
TimeOfDay startTime = TimeOfDay.now();